name: Run end-to-end tests

# PROCESS
#
# 1. Install all dependencies and spin off containers for all supported Python versions
# 2. Install pinned CDK version
# 3. Trade JWT token for AWS credentials to Test account
# 4. Run E2E in parallel for each feature

# USAGE
#
# see MAINTAINERS.md#internals for full details on mechanics.
#
# Always triggered on new PR merge.

on:
  workflow_dispatch:

  push:
    branches:
      - develop
    paths:
      - "aws_lambda_powertools/**"
      - "tests/e2e/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "mypy.ini"
      - "parallel_run_e2e.py"

# Maintenance: Add support for triggering on `run-e2e` label
# and enforce repo origin to prevent abuse

env:
  AWS_DEFAULT_REGION: us-east-1

concurrency: e2e

permissions:
  contents: read

jobs:
  run:
    runs-on: aws-powertools_ubuntu-latest_8-core
    permissions:
      id-token: write # needed to request JWT with GitHub's OIDC Token endpoint. docs: https://bit.ly/3MNgQO9
      contents: read  # checkout code
    strategy:
      fail-fast: false # needed so if a version fails, the others will still be able to complete and cleanup
      matrix:
        version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    if: ${{ github.actor != 'dependabot[bot]' && github.repository == 'aws-powertools/powertools-lambda-python' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Install poetry
        run: pipx install poetry
      - name: "Use Python"
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: ${{ matrix.version }}
          architecture: "x64"
          cache: "poetry"
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20.10.0"
      - name: Install CDK CLI
        run: |
          npm ci
          npx cdk --version
      - name: Install dependencies
        run: make dev
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        with:
          role-to-assume: ${{ secrets.AWS_TEST_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Test
        run: make e2e-test
